openapi: 3.0.0
info:
  title: Order Processing API
  version: 1.0.0
  description: API for processing customer orders.
paths:
  /orders:
    get:
      summary: Retrieve all orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    orderId:
                      type: integer
                    customerId:
                      type: integer
                    status:
                      type: string
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: integer
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      itemId:
                        type: integer
                      quantity:
                        type: integer
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                    type: integer
                  status:
                    type: string
